### ISSUE TITLE
Add ImGui::BeginTable Support?

### ISSUE THREAD

**Issue by 0400H** [pyimgui/pyimgui#196]
Recently, I want to achieve a feature just like:
https://github.com/ocornut/imgui/issues/125
or
![image](https://user-images.githubusercontent.com/16373603/102688599-bf499280-4232-11eb-9435-ae1dc609c8de.png)

But I did not find the api from：
https://pyimgui.readthedocs.io/en/latest/reference/imgui.core.html

What should I do to achieve this feature ?

**Comment by KinoxKlark** [comment]
Hi, unfortunately, this is not yet possible using pyimgui. The current version, 1.3.0, is based on imgui 1.65, and we are currently working on an upgrade to 1.79. As far as I know, Table features are not yet part of Imgui release but a work in progress that will come in future releases (already accessible via their master branch). On their latest release changelog, they say that this feature is in a finalization step, so we can hope to see this soon :)

For now, we focus our efforts on the upgrade to the latest official release of imgui. Experimental features _may_ come later for manual installation of pyimgui in a specific branch (like table, docking, multi-viewport, etc)

**Comment by Johndeep** [comment]
As far as I can tell, the current version 1.4.0 (or 1.4.1 from pip) is also based on 1.65 still. Since the attempt of basing it to 1.79 first, we are now at 1.82, which is currently available in the dev/version-2.0 branch. Which should have been quite a feat, since ocornut, the original author of imgui itself keeps frequently adding new features, which makes merging quite difficult.

It even went so fast, that the current version of imgui 1.87 does not work with my current c++ project any more, since it broke compatibility somewhere along the way and now also requires more header files. It seems that 1.82 is the last version, which still works fine by just replacing all header files without need for adjusting other files.

But long story short, rest assured, BeginTable was already added to imgui since 1.80, which is included in the dev/version-2.0 branch. For anyone, who might just discover this issue.

**Comment by kushalkolar** [comment]
v2.0 is out so I guess this is now available? https://github.com/pyimgui/pyimgui/releases/tag/2.0.0

**Comment by KinoxKlark** [comment]
Yes indeed, the release note lists all mapped functions:

> Mapping of table functionality: begin_table(), end_table(), table_next_row(), table_next_column(), table_set_column_index(), table_setup_column(), table_setup_scroll_freez(), table_headers_row(), table_header(), table_get_sort_specs(), table_get_column_count(), table_get_column_index(), table_get_row_index(), table_get_column_name(), table_get_column_flags(), table_set_background_color()
