### ISSUE TITLE
Cap Refresh rate

### ISSUE THREAD

**Issue by masc-it** [pyimgui/pyimgui#258]
Hello,
Is there a way to cap maximum fps? I'm using glfw backend and I am cranking more than 1200 FPS and 20% GPU utilization.
Yesterday I tried C++ imgui and it capped it at 60fps (my monitor refresh rate).
Btw, I am on windows 10.
At the moment I am using a dirty `time.sleep(0.0013)` in the main loop in order to slow it down (around 60fps), but I hope there's something better than this!

**Comment by KinoxKlark** [comment]
Hello,

What you are asking for is application-dependent and there is no universal solution. Moreover, this does not depend on `pyimgui` but on the used backend, i.e. GLFW in your case.

I am no expert of GLFW by any means, but it may propose a way to suggest a target framerate. It would however not be less of a crapy solution than yours. If you want to cap the framerate of your app, you probably will want to develop your own solution. You will need to measure time spent during each frame, and "wait" when your app is too fast (hopefully most of the time).

GLFW has a `glfwGetTime()` function, which should translate as `glfw.get_time()` in python binding (please check the documentation, I didn't verify myself).

A less crappy solution would be (in pseudocode):
```
while(true) {
    frame_start = getTime()
    ... // Frame Computation
    elapsed_time = getTime() - frame_start
    sleep(16ms - elapsed time)
}
```

Note however that the `sleep` proc may not be sufficiently precise, depending on your application you may choose to burn CPU cycle and only compute the frame every 60th of a second. (This may be overpowered for a windowed application but it is legit for a videogame that takes all the attention while it is running and needs precise framerate management). This will cap your GPU usage since render calls will only occur once every 16ms. This may look like
```
chrono_start = getTime()
while(true) {
    elapsed_time = getTime() - chrono_start
    if(elapsed_time >= 16ms)
    {
        chrono_start = getTime() // reset
        ... // Frame computation
    }
}
```
You can also choose to implement a mechanism to catch up if a frame takes too long. This may feel more responsive and consistent for the user
```
chrono_start = getTime()
while(true) {
    elapsed_time = getTime() - chrono_start
    if(elapsed_time > 16ms)
    {
        chrono_start += 16ms // will reduce future elapsed time by one frame, 
                             // if you are late of several frame it will continue at max FPS to catchup
        ... // Frame computation
    }
}
```
In fact, there are many more possibilities depending on your needs. You could decide to do catchup but only for a maximum of N frames then drop frames that are too late. You may choose to have different framerates for your mechanics and your renderer. You may have different threads that process data at different framerates, or that need to be combined at precise points of your frame. In a nutshell, this is a complex question that has a complex answer.

This does not depend on `pyimgui` which is only a light way addon to your application and does not manage the framerate. It depends on your application and the backend you use (which, btw, can be a custom backend too). If you need more information, I suggest you try to read about framerate and tick management in video games. As illustrated here with some examples, there are many possibilities and they may differ according to your needs. There are plenty of resources on the web.

I'll close this issue since it does not concern `pyimgui` directly. Feel free to comment if you think I missed something and think the issue should be reopened.
