### ISSUE TITLE
Help with Getting Started in Pyimgui

### ISSUE THREAD

**Issue by wquadri** [pyimgui/pyimgui#284]
Hi. I'm having trouble with getting anything to show up on screen. I've tried reading the documentation and tried the example on [docs home page](https://pyimgui.readthedocs.io/en/latest/guide/first-steps.html), but do not see anything. The command executes successfully using python3, but nothing shows up.

On initial install, I did

```
pip3 install imgui[full]
```

I'm not sure if I need any addition steps. I've only used tkinter before this and understand immediate mode is different. Just haven't gotten it to work yet. I'm not sure what the "wheels" mentioned in the documents are either. 

I'm running Ubuntu 22.04.

If any additional information is needed, I'd be happy to provide it. Any and all help is appreciated.

**Comment by KinoxKlark** [comment]
Hello, indeed, setting up pyimgui to show something requires a bit more work than the code presented on the home page. What you have to understand is that pyimgui in itself does not manage windows nor graphic pipeline; you have to do it yourself and explicitly tell pyimgui ho to use your graphic pipeline or windows events. This windows managing graphic pipeline thing is what we call a "backend".

Fortunately, you don't have to reinvent the wheel every time since we propose already implemented backends such as GLFW3, Pygame, etc... Which you have installed using the `pip xxx[full]` command. You can find full usage examples in https://github.com/pyimgui/pyimgui/tree/master/doc/examples . Those use the `imgui.integrations` submodule, which contains all the wiring work. So if you want to create your own backend in order to support a pipeline that we do not propose, you would need to take a look into those, but my guess is that for you, it is not necessary for the moment.

Let's quickly look at https://github.com/pyimgui/pyimgui/blob/master/doc/examples/integrations_glfw3.py (you may use another backend if you are more familiar with it, I use it as an example). This file contains the minimal code to create a window and manage events using GLFW3.

Start by importing modules
```python
import glfw # This is the backend
import OpenGL.GL as gl # Used to print stuff
import imgui # Pyimgui
from imgui.integrations.glfw import GlfwRenderer # The code that link pyimgui with GLFW
```

You then need to initialize GLFW, i.e. create a window, create an OpenGL context, and so on. Which is done in `def impl_glfw_init()`. Once you have initialized your window, you have to write your own loop as in `def main()` with
```python
while not glfw.window_should_close(window):
    glfw.poll_events()
    impl.process_inputs()

    imgui.new_frame()
        
    # Your application code ... Here you can use imgui, e.g. imgui.begin("Hello") ...

    gl.glClearColor(1., 1., 1., 1)
    gl.glClear(gl.GL_COLOR_BUFFER_BIT)

    imgui.render()
    impl.render(imgui.get_draw_data())
    glfw.swap_buffers(window)
``` 

Here with GLFW, we have to write our own event loop; I choose this example because it is the heart of the _Immediate Mode GUI_. But of course, if your backend is event-based, you would have to initialize and use the update events appropriately for the chosen framework. 

**Important Note:** The currently installable pyimgui version (through pip) is very old and lacks many functionalities. It is clearly usable, but you may end up frustrated by seeing that some functionalities of the cpp version now are missing. We are currently developing the next major release, version 2.0, which upgrades to a more recent version of the cpp lib, implements a tone of new functionalities, and fixes a lot of bugs. The dev branch is `dev/version-2.0` and should be stable enough for most use cases. If this is an option for you, I would suggest you manually install it from the dev branch in order to have the most "modern" experience. Any feedback would be helpful :)

I hope this will help you to bootstrap. Do not hesitate to ask if something isn't clear ;)

**Comment by wquadri** [comment]
This has helped me a lot. Thank you. If I do have any further questions, I'll be sure to ask. Going to try exploring on my own now and see what I can do.

**Comment by KinoxKlark** [comment]
You're welcome. I close this issue since it has been answered. Feel free to reopen it or open a new one if you have further questions :)

**Comment by wquadri** [comment]
Hello again. I've stumbled onto some input issues. I'm not sure how to have input fields retain text when I have multiple present

~~~
        imgui.begin('Corona Motor VIN Database', True)

    # draw text/input label inside of current window
        imgui.text('Invoice:')
        imgui.same_line()
        # changed, invNum = imgui.input_int2('', 0, 0, 8)
        # print(invNum)

        changed, test1 = imgui.input_text('', '', 18, 8)

        changed, vin = imgui.input_text('vin', '', 18, 8)

    # close current window context
        imgui.end()

~~~
![Screenshot from 2022-07-12 13-12-16](https://user-images.githubusercontent.com/13442123/178591373-ac671810-1392-4a58-abea-1f9daeef4728.png)
![Screenshot from 2022-07-12 13-12-29](https://user-images.githubusercontent.com/13442123/178591396-96e81cbb-eb12-4862-acfd-9143f7166aa2.png)

This is what I have so far. Whatever i type into the 'test1' input, whatever I have in 'vin' is removed.

Also had some trouble with leaving the labels blank, as it looks like by default the label  is placed after the input field. When I leave the labels blank, python interprets them as one and whats typed in one input field appears in all the others. My aim was to use 
~~~
imgui.text('Invoice')

imgui.same_line()

imgui.input_text('', '', 18, 8)

imgui.text('VIN')

imgui.same_line()

imgui.input_text('', '', 18, 8)
~~~

But not working as intended.

**Comment by learn-more** [comment]
That is because with an empty label, they have the same identifier.
If you want to use multiple inputs, but not display any text, give them a label with a `##` in it, so that the label has a unique id, but no text:
`imgui.input_text('##VIN', '', 18, 8)`

This is all documented in Dear Imgui itself btw...

**Comment by KinoxKlark** [comment]
Yes, moreover, concerning the content that is removed, it is because you pass an empty string to the `imgui.input_text` function. The string you pass in is the content that will be displayed (at least when the field has no focus and the user isn't editing it). Recall that in immediate mode, the whole GUI is redrawn every time, so the problem here is that once the user finishes editing the text input, this text input is redrawn with the content you pass in, i.e. an empty string.

The correct way to do it is to declare a buffer variable outside the main loop and pass it as input. Then you get back the modified (or unmodified) text and assign it to the chosen buffer. For example:

```python
buffer = "Default Value" # you can use an empty string as the default one of course
while not glfw.window_should_close(window):
    # ... 
    imgui.begin("My Form")
    _, buffer = imgui.input_text("##Test", buffer, 100)
    imgui.end()
```
Here 100 is the max number of characters that will be used.

**Comment by wquadri** [comment]
After looking the code over a few times I understood what I was doing incorrectly with the labels. 

And my friend pointed me in the direction of having the variables initiated outside of the loop. 

I was mainly looking at the pyimgui documentation. I will be sure to check out the source documentation if I need more help. Thank you both for your insights. Appreciate your time.
